[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0" , features = ["ssr"]}
frontend = { path = "../frontend" }
actix-web = "^4"
actix-files = "0.6"
